services:
  - type: web
    name: whatsapp-meta
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_VERIFY_TOKEN
        sync: false
      - key: VITE_API_BEARER_TOKEN
        sync: false

